[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['base64-sol/=node_modules/base64-sol/', '@openzeppelin/=node_modules/@openzeppelin/', '@rari-capital/=node_modules/@rari-capital/', 'eth-gas-reporter/=node_modules/eth-gas-reporter/', 'hardhat/=node_modules/hardhat/', '@chainlink/=node_modules/@chainlink/', '@ensdomains/=node_modules/@ensdomains/', 'ds-test/=lib/ds-test/src/', '@opengsn/=node_modules/@opengsn/']
optimizer = true
optimizer_runs = 99999
solc_version = "0.8.11"
cache = true
chain_id = 80001
