[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'base64/=/lib/base64/',
    'solmate/=/lib/solmate/',
    'ds-test/=/lib/ds-test/src/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@chainlink/=node_modules/@chainlink/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@opengsn/=node_modules/@opengsn/'
]
optimizer = true
optimizer_runs = 99999
solc_version = "0.8.12"
cache = true
chain_id = 80001
