name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@3.0.2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@latest
        with:
          version: latest
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run tests
        run: forge test -vvvv --contracts contracts --gas-report

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        with:
          target: 'contracts/'
          solc-version: "0.8.13"
          node-version: 16
      #     sarif: results.sarif

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}

      - name: Mock Deploy
        run: pnpm deployV2:local

