name: "Test Contracts"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: Test Contracts
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: ZK Setup
      run: yarn zk:setup
    - name: Test Contracts
      run: yarn test
