name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install


      - name: Run tests
        run: forge test -vvvv --contracts contracts --gas-report

      # - name: Install Solidity
      #   env:
      #     SOLC_VERSION: 0.8.13
      #   run: |
      #     pip3 install solc-select
      #     solc-select install $SOLC_VERSION
      #     solc-select use $SOLC_VERSION

      # - name: Install Slither
      #   env:
      #     SLITHER_VERSION: 0.8.2
      #   run: pip3 install slither-analyzer==$SLITHER_VERSION

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}

      # - name: Run Slither
      #   run: slither ./contracts --config slither.config.json

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        with:
          target: 'contracts/'
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

      - name: Mock Deploy
        run: pnpm deployV2:local

